#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

GH_API=https://api.github.com/repos/Elgg/Elgg/releases/latest
LATEST=$(curl -s $GH_API | grep -oP '"tag_name": "\K(.*)(?=")')
VERSION=${LATEST#v}
dl http://elgg.org/download/elgg-${VERSION}.zip /usr/local/src
