#!/bin/sh -ex

DB_NAME=elgg
DB_USER=elgg
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/elgg
ELGG_DATA=/var/lib/elgg/data

