#!/bin/sh -ex

DB_NAME=elgg
DB_USER=elgg
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/elgg

ELGG_ROOT=/var/www/elgg/vendor/elgg/elgg

ELGG_DATA=/var/lib/elgg/data

# unpack and set permissions
unzip $SRC/elgg-*.zip -d $(dirname $WEBROOT)
rm $SRC/elgg-*.zip
mv $(dirname $WEBROOT)/elgg-* $WEBROOT
chown -R root:root $WEBROOT

# setup elgg data directory
mkdir -p $ELGG_DATA
chown -R www-data:www-data $ELGG_DATA

# configure apache
a2dissite 000-default
a2enmod headers
a2ensite elgg
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"
$MYSQL_BATCH --execute "INSTALL SONAME 'ha_archive';"

# cli based installation
rm $WEBROOT/.htaccess
chown -R www-data:www-data $WEBROOT
chown -R www-data:www-data $ELGG_DATA
INSTALLER=$ELGG_ROOT/install/cli/sample_installer.php

# database settings
sed -i "s|'dbuser'.*|'dbuser' => '$DB_USER',|" $INSTALLER
sed -i "s|'dbpassword'.*|'dbpassword' => '$DB_PASS',|" $INSTALLER
sed -i "s|'dbname'.*|'dbname' => '$DB_NAME',|" $INSTALLER

# site settings
sed -i "s|'sitename'.*|'sitename' => 'TurnKey Elgg',|" $INSTALLER
sed -i "s|'siteemail'.*|'siteemail' => '$ADMIN_MAIL',|" $INSTALLER
sed -i "s|'wwwroot'.*|'wwwroot' => 'https://$DOMAIN',|" $INSTALLER
sed -i "s|'dataroot'.*|'dataroot' => '$ELGG_DATA',|" $INSTALLER

# admin settings
sed -i "s|'displayname'.*|'displayname' => 'Administrator',|" $INSTALLER
sed -i "s|'email'.*|'email' => '$ADMIN_MAIL',|" $INSTALLER
sed -i "s|'username'.*|'username' => '$ADMIN_NAME',|" $INSTALLER
sed -i "s|'password'.*|'password' => '$ADMIN_PASS',|" $INSTALLER

sed -i "s|\$enabled = false;|\$enabled = true;|" $INSTALLER

su -s /bin/sh -c "php $INSTALLER" www-data
rm $INSTALLER

sed -i 's/{{timezone}}/UTC/' $WEBROOT/elgg-config/settings.php

chown -R root:root $WEBROOT
chown -R root:root $ELGG_ROOT
chmod 644 $WEBROOT/elgg-config/settings.php

# add TurnKey credit

sed -i "s|^ \\+\\(elgg_register_ajax_view('navigation/menu/user_hover/contents');\\)$|\
        elgg_register_menu_item('footer', \\ElggMenuItem::factory(array(\n\
                'name' => 'tklpowered',\n\
                'text' => 'Powered by TurnKey Linux',\n\
                'href' => 'http://turnkeylinux.org',\n\
                'title' => 'TurnKey Linux',\n\
                'section' => 'meta',\n\
        )));\n\
\n\
        \1|" \
$ELGG_ROOT/engine/lib/navigation.php

# stop services
service mysql stop
service apache2 stop

