#!/bin/bash -ex

DB_NAME=elgg
DB_USER=elgg
DB_PASS=$(mcookie)

ADMIN_NAME="admin"
ADMIN_PASS="turnkey"
ADMIN_EMAIL="admin@example.com"
DOMAIN="www.example.com"

WEBROOT="/var/www/elgg"
ELGG_DATA="$(dirname "$WEBROOT")/elgg-data"

mkdir -p "$ELGG_DATA"
mkdir -p "$(dirname "$WEBROOT")"/.composer
chown -R www-data:www-data "$ELGG_DATA"

if [[ -n "$FAB_HTTP_PROXY" ]]; then
    export http_proxy="$FAB_HTTP_PROXY"
    export https_proxy="$FAB_HTTP_PROXY"
fi

echo y | turnkey-composer create-project elgg/starter-project:dev-master $WEBROOT
cd "$WEBROOT"
turnkey-composer install
turnkey-composer install # 2nd run is req'd apparently...

cat > /tmp/install.php <<EOF
<?php
  return array(
    "timezone" => "UTC",
    "dataroot" => "$ELGG_DATA",
    "wwwroot" => "https://$DOMAIN/",
    "dbuser" => "$DB_USER",
    "dbpassword" => "$DB_PASS",
    "dbname" => "$DB_NAME",
    "dbhost" => "localhost",
    "dbport" => "3306",
    "dbprefix" => "elgg_",
    "sitename" => "TurnKey Elgg",
    "siteemail" => "$ADMIN_EMAIL",
    "displayname" => "Administrator",
    "email" => "$ADMIN_EMAIL",
    "username" => "$ADMIN_NAME",
    "password" => "$ADMIN_PASS"
  );
?>
EOF

# configure apache
a2dissite 000-default
a2enmod headers
a2ensite elgg
a2enmod rewrite
a2enmod cache

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --batch --execute"

mysqladmin  create $DB_NAME
$MYSQL_BATCH "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"
$MYSQL_BATCH "INSTALL SONAME 'ha_archive';"

# cli based installation
turnkey-elgg-cli install --config /tmp/install.php
rm /tmp/install.php

sed -i 's/{{timezone}}/UTC/' $WEBROOT/elgg-config/settings.php

# enable simplecache by default
sed -Ei "\|$CONFIG->simplecache_enabled| s|^//(.*)=.*|\1= true;|" $WEBROOT/elgg-config/settings.php

chown -R root:root $WEBROOT
chmod 644 $WEBROOT/elgg-config/settings.php

# add TurnKey credit
# currently not working - see https://github.com/turnkeylinux/tracker/issues/1906
sed -i "s|^ \\+\\(elgg_register_ajax_view('navigation/menu/user_hover/contents');\\)$|\
        elgg_register_menu_item('footer', \\ElggMenuItem::factory(array(\n\
                'name' => 'tklpowered',\n\
                'text' => 'Powered by TurnKey Linux',\n\
                'href' => 'https://turnkeylinux.org',\n\
                'title' => 'TurnKey Linux',\n\
                'section' => 'meta',\n\
        )));\n\
\n\
        \1|" \
"$WEBROOT"/vendor/elgg/elgg/engine/lib/navigation.php

# stop services
service mysql stop
service apache2 stop

unset http_proxy https_proxy
