#!/bin/bash -e
# regenerate elgg mysql password

. /etc/default/inithooks

CONF=/var/www/elgg/elgg-config/settings.php

PASSWORD=$(mcookie)
sed -i "s|^\$CONFIG->dbpass.*|\$CONFIG->dbpass = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=elgg --pass="$PASSWORD"
