#!/bin/bash -e
# set elgg admin password and email, and domain to serve

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/elgg.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"

