ServerName localhost

<VirtualHost *:80>
    UseCanonicalName Off
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    # redirect to configured domain or IP (updated by inithook)
    RewriteRule ^/(.*) https://localhost/$1 [R=307,L]
    # recommended redirect in production is 308 - permanent
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/elgg/
    RewriteEngine On
    # redirect to configured domain or IP (updated by inithook)
    RewriteCond %{HTTP_HOST} !^localhost$
    RewriteRule ^/(.*) https://localhost/$1 [R=307,L]
    # recommended redirect in production is 308 - permanent

    # elgg specific conf - taken from
    # https://github.com/Elgg/Elgg/blob/7.x/install/config/htaccess.dist
    DirectoryIndex index.php
    AddType image/vnd.microsoft.icon .ico
    ExpiresActive On
    ExpiresDefault "access plus 1 year"
    <FilesMatch "\.(jpg|jpeg|gif|png|mp3|flv|mov|avi|3pg|html|htm|swf|js|mjs|css|ico)$">
        FileETag MTime Size
    </FilesMatch>
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [QSA,L]

    # security hardening
    RewriteRule (^\.|/\.) - [F]
    RewriteRule /?(composer\.json|composer\.lock)$ - [F]
    # see Elgg example conf for more hardening options
    # https://github.com/Elgg/Elgg/blob/7.x/install/config/htaccess.dist
</VirtualHost>

<Directory /var/www/elgg/>
    Options -MultiViews -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<Location /cron>
    Require local
</Location>
